site_name: lambda-abstraction
site_url: https://lambda-abstraction.github.io/lambda-abstraction
repo_url: https://github.com/lambda-abstraction/lambda-abstraction
nav:
  - what is this: index.md
  - python-typehints: 
    - introduction: python-typehints/index.md
    - builtin-types: python-typehints/builtin-types.md
    - duck-typing: python-typehints/duck-typing.md
    - defining-generics: python-typehints/defining-generics.md
    - type-aliases: python-typehints/type-aliases.md
    - type-variable-bounds-and-constraints: python-typehints/type-variable-bounds-and-constraints.md
  - wip-hints:
    - introduction: wip-hints/index.md
    - duck-typing: wip-hints/duck-typing.md
theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy
    - content.code.annotate 
  icon:
    annotation: material/star-four-points-circle
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
